export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const FECTH_CATEGORIES = 'FECTH_CATEGORIES';
export const FECTH_CATEGORIES_SUCCESS = 'FECTH_CATEGORIES_SUCCESS';
export const FECTH_CATEGORIES_FAILURE = 'FECTH_CATEGORIES_FAILURE';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
